/**
 * @aibtc/mcp-server tools the keyless remote server registers.
 *
 * A tool is listed only if it works with no wallet, key or local file: every
 * address it needs is an input, it never signs or pays, it reads no
 * ~/.aibtc state, and it fetches no caller-supplied URL. broadcast_transaction
 * and psbt_broadcast are included because they relay a transaction the caller
 * already signed.
 *
 * Not listed, with the reason:
 * - get_nft_owner, alex_get_swap_quote, alex_get_pool_info,
 *   yield_dashboard_overview, yield_dashboard_positions, legion_my_position,
 *   psbt_create_ordinal_buy: always read the active wallet address
 * - bitflow_get_keeper_contract: creates a keeper contract (third-party write)
 * - pillar_*dca_partners, pillar_*dca_leaderboard, nonce_health,
 *   tx_status_deep, arxiv_list_digests: read ~/.aibtc state
 * - probe_x402_endpoint, nostr_read_feed, nostr_search_tags, nostr_get_profile,
 *   inference_*: fetch a caller-supplied URL or relay
 * - scaffold_*: write a project to the server's disk
 */
export const REMOTE_TOOLS: ReadonlySet<string> = new Set([
  // Stacks chain
  "get_transaction_status",
  "get_stx_fees",
  "get_block_info",
  "get_mempool_info",
  "get_contract_info",
  "get_contract_events",
  "get_network_status",
  "call_read_only_function",
  "get_stx_balance",
  "get_account_info",
  "get_account_transactions",
  "broadcast_transaction",
  // sBTC
  "sbtc_withdrawal_status",
  "sbtc_withdraw_status",
  "sbtc_get_deposit_info",
  "sbtc_get_peg_info",
  "sbtc_deposit_status",
  "sbtc_get_balance",
  // Tokens / NFTs
  "get_token_info",
  "get_token_holders",
  "get_nft_metadata",
  "get_collection_info",
  "get_nft_history",
  "get_token_balance",
  "list_user_tokens",
  "get_nft_holdings",
  // Stacking
  "get_pox_info",
  "list_stacking_signers",
  "stackspot_list_pots",
  "stackspot_get_pot_state",
  "get_stacking_status",
  "get_stacking_rewards",
  "dual_stacking_status",
  "dual_stacking_get_rewards",
  // BNS
  "lookup_bns_name",
  "get_bns_info",
  "check_bns_availability",
  "get_bns_price",
  "reverse_bns_lookup",
  "list_user_domains",
  // Identity / reputation (ERC-8004)
  "identity_get_last_id",
  "identity_get",
  "identity_get_metadata",
  "reputation_get_summary",
  "reputation_get_clients",
  "reputation_get_feedback_count",
  "reputation_get_approved_limit",
  "reputation_get_last_index",
  "reputation_read_feedback",
  "reputation_read_all_feedback",
  // Discovery / earning
  "list_x402_endpoints",
  "earning_opportunities",
  "bounty_list",
  "bounty_get",
  "bounty_submissions",
  // DeFi
  "alex_list_pools",
  "zest_list_assets",
  "zest_get_position",
  "bitflow_get_ticker",
  "bitflow_get_tokens",
  "bitflow_get_swap_targets",
  "bitflow_get_quote",
  "bitflow_get_routes",
  "bitflow_get_order",
  "bitflow_get_keeper_user",
  "styx_pool_status",
  "styx_pools",
  "styx_price",
  "styx_fees",
  "styx_status",
  "styx_history",
  "yield_dashboard_apy_breakdown",
  "pillar_direct_quote",
  "pillar_direct_resolve_recipient",
  "jingswap_get_cycle_state",
  "jingswap_get_depositors",
  "jingswap_get_user_deposit",
  "jingswap_get_settlement",
  "jingswap_get_cycles_history",
  "jingswap_get_user_activity",
  "jingswap_get_prices",
  "tenero_token_info",
  "tenero_market_summary",
  "tenero_market_stats",
  "tenero_top_gainers",
  "tenero_top_losers",
  "tenero_trending_pools",
  "tenero_wallet_trades",
  "tenero_whale_trades",
  "tenero_holder_stats",
  "tenero_wallet_holdings",
  "tenero_search",
  // Markets / governance
  "stacks_market_list",
  "stacks_market_search",
  "stacks_market_get",
  "stacks_market_quote_buy",
  "stacks_market_quote_sell",
  "stacks_market_get_position",
  "legion_status",
  "legion_list_stories",
  "legion_get_story",
  "atstake_market_status",
  "atstake_subject",
  "atstake_position",
  "atstake_get_bid",
  "atstake_legion_status",
  "atstake_legion_list_proposals",
  "atstake_legion_get_proposal",
  // Bitcoin L1 / ordinals / runes
  "get_btc_fees",
  "get_btc_mempool_info",
  "get_btc_transaction_status",
  "get_btc_address_txs",
  "get_btc_balance",
  "get_btc_utxos",
  "get_cardinal_utxos",
  "get_ordinal_utxos",
  "get_inscriptions_by_address",
  "get_inscription",
  "estimate_inscription_fee",
  "estimate_child_inscription_fee",
  "ordinals_get_listings",
  "ordinals_p2p_list_trades",
  "ordinals_p2p_get_trade",
  "ordinals_p2p_agents",
  "souldinals_list_souls",
  "souldinals_load_soul",
  "souldinals_display_soul",
  "runes_list_etchings",
  "runes_get_etching",
  "runes_get_holders",
  "runes_get_activity",
  "runes_get_address_balances",
  "runes_get_address_activity",
  "get_rune_balances",
  "get_rune_utxos",
  "psbt_decode",
  "psbt_broadcast",
  // Verify / hash / guides
  "sip018_verify",
  "sip018_hash",
  "stacks_verify_message",
  "btc_verify_message",
  "schnorr_verify_digest",
  "taproot_verify_cosig",
  "taproot_multisig_guide",
  "openrouter_integration_guide",
  "openrouter_models",
  "get_server_version",
  // Ops / research
  "check_relay_health",
  "nostr_relay_list",
  "arxiv_search",
  "arxiv_compile_digest",
]);
